
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Entry Corporation;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Entry Recruiting;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Entry Person;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Label StreetLabel;
	
	private global::Gtk.Entry Street;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.Label label10;
	
	private global::Gtk.Entry City;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.HBox hbox10;
	
	private global::Gtk.Label label18;
	
	private global::Gtk.CheckButton checkbutton1;
	
	private global::Gtk.Label label19;
	
	private global::Gtk.Label label20;
	
	private global::Gtk.Entry Salary;
	
	private global::Gtk.HBox hbox9;
	
	private global::Gtk.Label label16;
	
	private global::Gtk.Entry Email;
	
	private global::Gtk.HBox hbox8;
	
	private global::Gtk.Label label12;
	
	private global::Gtk.Label label13;
	
	private global::Gtk.Entry JobNumber;
	
	private global::Gtk.Label label15;
	
	private global::Gtk.Entry JobPosition;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.HBox hbox7;
	
	private global::Gtk.Label label11;
	
	private global::Gtk.ComboBox LetterOpeningCombo;
	
	private global::Gtk.Entry LetterOpeningPerson;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Job applications");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		this.vbox1.BorderWidth = ((uint)(6));
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.Xalign = 0F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Corporation");
		this.hbox2.Add (this.label5);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label5]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.Corporation = new global::Gtk.Entry ();
		this.Corporation.CanFocus = true;
		this.Corporation.Name = "Corporation";
		this.Corporation.IsEditable = true;
		this.Corporation.InvisibleChar = '●';
		this.hbox2.Add (this.Corporation);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.Corporation]));
		w2.Position = 1;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.Xalign = 0F;
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Recruiting");
		this.hbox3.Add (this.label6);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label6]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.Recruiting = new global::Gtk.Entry ();
		this.Recruiting.CanFocus = true;
		this.Recruiting.Name = "Recruiting";
		this.Recruiting.IsEditable = true;
		this.Recruiting.InvisibleChar = '●';
		this.hbox3.Add (this.Recruiting);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.Recruiting]));
		w5.Position = 1;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.Xalign = 0F;
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Person");
		this.hbox1.Add (this.label7);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label7]));
		w7.Position = 0;
		w7.Expand = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.Person = new global::Gtk.Entry ();
		this.Person.CanFocus = true;
		this.Person.Name = "Person";
		this.Person.IsEditable = true;
		this.Person.InvisibleChar = '●';
		this.hbox1.Add (this.Person);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.Person]));
		w8.Position = 1;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.StreetLabel = new global::Gtk.Label ();
		this.StreetLabel.Name = "StreetLabel";
		this.StreetLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Street");
		this.hbox4.Add (this.StreetLabel);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.StreetLabel]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.Street = new global::Gtk.Entry ();
		this.Street.CanFocus = true;
		this.Street.Name = "Street";
		this.Street.IsEditable = true;
		this.Street.InvisibleChar = '●';
		this.hbox4.Add (this.Street);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.Street]));
		w11.Position = 1;
		this.vbox1.Add (this.hbox4);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
		w12.Position = 3;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("City");
		this.hbox6.Add (this.label10);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label10]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.City = new global::Gtk.Entry ();
		this.City.CanFocus = true;
		this.City.Name = "City";
		this.City.IsEditable = true;
		this.City.InvisibleChar = '●';
		this.hbox6.Add (this.City);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.City]));
		w14.Position = 1;
		this.vbox1.Add (this.hbox6);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox6]));
		w15.Position = 4;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Create application");
		this.vbox1.Add (this.button1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.button1]));
		w16.PackType = ((global::Gtk.PackType)(1));
		w16.Position = 5;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label18 = new global::Gtk.Label ();
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Salary");
		this.hbox10.Add (this.label18);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label18]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.checkbutton1 = new global::Gtk.CheckButton ();
		this.checkbutton1.CanFocus = true;
		this.checkbutton1.Name = "checkbutton1";
		this.checkbutton1.Label = "";
		this.checkbutton1.DrawIndicator = true;
		this.checkbutton1.UseUnderline = true;
		this.hbox10.Add (this.checkbutton1);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.checkbutton1]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label19 = new global::Gtk.Label ();
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Meine Gehaltsvorstellungen liegen zwischen");
		this.hbox10.Add (this.label19);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label19]));
		w19.Position = 2;
		w19.Expand = false;
		w19.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.label20 = new global::Gtk.Label ();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Euro brutto im Jahr.");
		this.hbox10.Add (this.label20);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label20]));
		w20.PackType = ((global::Gtk.PackType)(1));
		w20.Position = 3;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.Salary = new global::Gtk.Entry ();
		this.Salary.CanFocus = true;
		this.Salary.Name = "Salary";
		this.Salary.Text = global::Mono.Unix.Catalog.GetString ("56 000,- und 66 000,-");
		this.Salary.IsEditable = true;
		this.Salary.InvisibleChar = '●';
		this.hbox10.Add (this.Salary);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.Salary]));
		w21.PackType = ((global::Gtk.PackType)(1));
		w21.Position = 4;
		this.vbox1.Add (this.hbox10);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox10]));
		w22.PackType = ((global::Gtk.PackType)(1));
		w22.Position = 6;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.label16 = new global::Gtk.Label ();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("E-Mail");
		this.hbox9.Add (this.label16);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label16]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.Email = new global::Gtk.Entry ();
		this.Email.CanFocus = true;
		this.Email.Name = "Email";
		this.Email.IsEditable = true;
		this.Email.InvisibleChar = '●';
		this.hbox9.Add (this.Email);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.Email]));
		w24.Position = 1;
		this.vbox1.Add (this.hbox9);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox9]));
		w25.PackType = ((global::Gtk.PackType)(1));
		w25.Position = 7;
		w25.Expand = false;
		w25.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Position");
		this.hbox8.Add (this.label12);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label12]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Bewerbung auf die Stelle");
		this.hbox8.Add (this.label13);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label13]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.JobNumber = new global::Gtk.Entry ();
		this.JobNumber.CanFocus = true;
		this.JobNumber.Name = "JobNumber";
		this.JobNumber.IsEditable = true;
		this.JobNumber.InvisibleChar = '●';
		this.hbox8.Add (this.JobNumber);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.JobNumber]));
		w28.Position = 2;
		// Container child hbox8.Gtk.Box+BoxChild
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("als");
		this.hbox8.Add (this.label15);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label15]));
		w29.Position = 3;
		w29.Expand = false;
		w29.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.JobPosition = new global::Gtk.Entry ();
		this.JobPosition.CanFocus = true;
		this.JobPosition.Name = "JobPosition";
		this.JobPosition.IsEditable = true;
		this.JobPosition.InvisibleChar = '●';
		this.hbox8.Add (this.JobPosition);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.JobPosition]));
		w30.Position = 4;
		this.vbox1.Add (this.hbox8);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox8]));
		w31.PackType = ((global::Gtk.PackType)(1));
		w31.Position = 8;
		w31.Expand = false;
		w31.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Letter opening");
		this.hbox7.Add (this.label11);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label11]));
		w32.Position = 0;
		w32.Expand = false;
		w32.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.LetterOpeningCombo = global::Gtk.ComboBox.NewText ();
		this.LetterOpeningCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Sehr geehrte Damen und Herren"));
		this.LetterOpeningCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Sehr geehrte Frau"));
		this.LetterOpeningCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Sehr geehrter Herr"));
		this.LetterOpeningCombo.Name = "LetterOpeningCombo";
		this.LetterOpeningCombo.Active = 0;
		this.hbox7.Add (this.LetterOpeningCombo);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.LetterOpeningCombo]));
		w33.Position = 1;
		w33.Expand = false;
		w33.Fill = false;
		this.hbox5.Add (this.hbox7);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.hbox7]));
		w34.Position = 0;
		w34.Expand = false;
		w34.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.LetterOpeningPerson = new global::Gtk.Entry ();
		this.LetterOpeningPerson.CanFocus = true;
		this.LetterOpeningPerson.Name = "LetterOpeningPerson";
		this.LetterOpeningPerson.IsEditable = true;
		this.LetterOpeningPerson.InvisibleChar = '●';
		this.hbox5.Add (this.LetterOpeningPerson);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.LetterOpeningPerson]));
		w35.PackType = ((global::Gtk.PackType)(1));
		w35.Position = 1;
		this.vbox1.Add (this.hbox5);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
		w36.PackType = ((global::Gtk.PackType)(1));
		w36.Position = 9;
		w36.Expand = false;
		w36.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1017;
		this.DefaultHeight = 318;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
	}
}
